### ISSUE TITLE
AsyncTask's onPostExecute not called due to wrong method overriding

### ISSUE THREAD

**Issue by ericafenyo** [e-mission/cordova-server-sync#37] opened 2020-02-25 12:43 UTC
The `onPostExecute()` of the current AsyncTask implementation does not override the superclass' hence the  `cachedCallbackContext.success()` is never called
```java
// cordova-server-sync/src/android/ServerSyncPlugin.java : line 70
            AsyncTask<Context, Void, Void> task = new AsyncTask<Context, Void, Void>() {
               ...

                protected void onPostExecute(Long result) {
                    cachedCallbackContext.success();
                }
            };
```
The solution was to pass `Void` as an argument instead of `Long` . I forked this repo and made the necessary changes however I was not able to add the forked version to my cordova project (e-mission-phone);

Error while adding the forked version.
``` bash
$ cordova plugin add https://github.com/ericafenyo/cordova-server-sync.git

Failed to fetch plugin https://github.com/ericafenyo/cordova-server-sync.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

Error when added to the `config.xml`
```xml
<plugin name="edu.berkeley.eecs.emission.cordova.serversync" spec="https://github.com/ericafenyo/cordova-server-sync.git" />
```

``` bash
$ cordova prepare
...
Discovered plugin "edu.berkeley.eecs.emission.cordova.serversync" in config.xml. Adding it to the project
Failed to restore plugin "edu.berkeley.eecs.emission.cordova.serversync" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin https://github.com/ericafenyo/cordova-server-sync.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by shankari** [comment] 2020-02-25 16:59
I just checked https://github.com/ericafenyo/cordova-server-sync.git and there does not currently appear to be any differences.
https://github.com/e-mission/cordova-server-sync/compare/master...ericafenyo:master

So:
1. are you able to add https://github.com/e-mission/cordova-server-sync.git successfully?
1. If not, which version of cordova-android are you on? Is it the same as the `README`?

Also, I am so glad you are cleaning up the sync code - it definitely needs it :) I would appreciate it if you would submit such changes as pull requests...

**Comment by ericafenyo** [comment] 2020-02-25 21:13
@shankari  Thank you for your quick response.

> 1. are you able to add https://github.com/e-mission/cordova-server-sync.git successfully?

Yes, I was able to add the original plugin without any problem and I am using Cordova version 8.1.2 as stated in the docs.

Also, I think it is better to create a pull request to resolve this issue at once.
https://github.com/e-mission/cordova-server-sync/pull/38

**Comment by shankari** [comment] 2020-02-26 06:22
I can reproduce this.

```
# cordova plugin add https://github.com/ericafenyo/cordova-server-sync.git
(node:6621) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/ericafenyo/cordova-server-sync.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /root/.nvm/versions/node/v9.4.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
```

I see similar behavior in my fork 

```
# cordova plugin add https://github.com/shankari/cordova-server-sync.git
(node:6716) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/shankari/cordova-server-sync.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /root/.nvm/versions/node/v9.4.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
```

I wonder if this is because the cordova plugin code cannot deal with forks, only with the upstream repo.

I have not run into this before because I typically don't check in my code until I have finished testing it. In order to test my code, I just make the changes locally and then add the plugin using the path to the local repo - e.g. 

```
$ cordova plugin add ~/plugins/cordova-server-sync
```

Can you try out that approach?

I can investigate this further, but I'm also quite busy, and I'm not sure I want to go down the rabbit hole of cordova plugins if there is a simple workaround.

**Comment by shankari** [comment] 2020-02-26 06:43
> I can investigate this further, but I'm also quite busy, and I'm not sure I want to go down the rabbit hole of cordova plugins if there is a simple workaround.

I am curious, so I am going to go a little bit into the rabbit hole.

The error reported is `Failed to get absolute path to installed module`
Grepping through the cordova scripts, we find that this is from the `cordova-fetch` module.

```
function getPath (id, dest, target) {
    var destination = path.resolve(path.join(dest, id));
    var finalDest = fs.existsSync(destination) ? destination : searchDirForTarget(dest, target);

    if (!finalDest) {
        throw new CordovaError('Failed to get absolute path to installed module');
    }

    return finalDest;
}
```

Adding additional logging, 

```
    console.log("while finding ("+ id + ", " + dest + ","+ target + ")," +
        "destination = "+destination+" finalDest = "+finalDest);
```

we get 

#### working (from the e-mission repo)

```
while finding (cordova-server-sync, /e-mission-phone/node_modules,https://github.com/e-mission/cordova-server-sync.git#master),destination = /e-mission-phone/node_modules/cordova-server-sync finalDest = /e-mission-phone/node_modules/em-cordova-server-sync
```

#### not working (from the ericafenyo repo)

```
while finding (cordova-server-sync, /e-mission-phone/node_modules,https://github.com/ericafenyo/cordova-server-sync.git#master),destination = /e-mission-phone/node_modules/cordova-server-sync finalDest = undefined
```

**Comment by shankari** [comment] 2020-02-26 07:03
Looking at the implementation of `searchDirForTarget`, which seems to be the main difference, we see this comment

```
 * Make an additional search in destination folder using repository.url property from package.json
```

Aha! The [`repository.url`](https://github.com/e-mission/cordova-server-sync/blob/master/package.json#L15) is the e-mission repo.

So while modifying a plugin, you need to test it by adding it from the filesystem. Then once the change is merged to the e-mission repo, the plugin can be updated from github.

**Comment by shankari** [comment] 2020-02-26 07:04
@ericafenyo can you also submit a documentation PR which outlines this process? Thanks!
Once you have tested https://github.com/e-mission/cordova-server-sync/pull/38 locally, I can merge it and bump up the version number.

**Comment by ericafenyo** [comment] 2020-02-26 18:04
@shankari Thank you for the information.
> I have not run into this before because I typically don't check in my code until I have finished testing it. In order to test my code, I just make the changes locally and then add the plugin using the path to the local repo - e.g.
>
> $ cordova plugin add ~/plugins/cordova-server-sync
> Can you try out that approach?

Yea. I created a `plugins` folder, cloned my `cordova-server-sync` fork  and  added it as a local plugin to my e-mission project using `cordova plugin add ~/plugins/cordova-server-sync.`
The changes made to the AsyncTask worked as expected and the [forceSync's](https://github.com/e-mission/cordova-server-sync/blob/b9a0a7eda58a6335c7af4b626b274e7ef05fe178/www/ui/ionic/js/sync-settings.js#L109) success method was invoked which wasn't the case at first.

I also modified the[ repository.url](https://github.com/ericafenyo/cordova-server-sync/blob/9a5db8c43944eaaab358f0bbe018d2e72007ac53/package.json#L15) in the `package.json` to point to my repository and that resolved the [Failed to get absolute path to installed module](https://github.com/e-mission/cordova-server-sync/issues/37#issuecomment-591261144) issue.

> @ericafenyo can you also submit a documentation PR which outlines this process? Thanks!

Can you clarified on the specific process to document and the file(README.md?) to use, please?

Thanks again for your help.

**Comment by shankari** [comment] 2020-02-27 00:08
> I also modified the repository.url in the package.json to point to my repository and that resolved the Failed to get absolute path to installed module issue.

For the record, you don't need this if you are testing using the local copy of the plugin

> Can you clarified on the specific process to document and the file(README.md?) to use, please?

The process of testing changes to a plugin - essentially what you did for "I created a plugins folder, cloned my...."

Let's put this in the documentation repo https://github.com/e-mission/e-mission-docs
I already have similar instructions in the README.md for the data collection (https://github.com/e-mission/e-mission-data-collection), but you didn't see it because it is not in this repo. Since these are generic instructions for changing **any** plugin, let's put them in the docs repository.

**Closed as completed** 2020-02-27 01:00 UTC
